// <auto-generated />
namespace InspectionApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit6));
        
        string IMigrationMetadata.Id
        {
            get { return "201711230552501_edit6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
